### ISSUE TITLE
Not compatible with ZF2 >2.5.3

### ISSUE THREAD

**Issue by pensiero** [neilime/zf2-mobile-detect#3]
I'm receiving this warning:

> You are retrieving the service locator from within the class MyApplication\Controller\IndexController. Please be aware that ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer. You will need to update your class to accept all dependencies at creation, either via constructor arguments or setters, and use a factory to perform the injections

The problem is here:
https://github.com/hschapitz/zf2-mobile-detect/blob/master/src/MobileDetect/Mvc/Controller/Plugin/MobileDetectPlugin.php#L14

And probably will be also here:
https://github.com/neilime/zf2-mobile-detect/blob/master/src/MobileDetect/View/Helper/MobileDetectHelper.php#L15

**Comment by pensiero** [comment]
I opened this PR: https://github.com/neilime/zf2-mobile-detect/pull/4

**Comment by neilime** [comment]
Thanks to your PR, its compatible now (tag 2.0.0).
