### ISSUE TITLE
ZF2 support

### ISSUE THREAD

**Issue by LukasVice** [neilime/zf2-mobile-detect#7]
Hi,
I'm using your library with ZF2. Unfortunately, with your latest commit I'm not able to use this library anymore because it requires ZF3 now.
Could you please add ZF2 support again? Or tag the latest version which supports ZF2?
Thanks for your work!

**Comment by pensiero** [comment]
@neilime is the latest release retrocompatibile with ZF2?
in case, I can send a PR and change this line of composer: https://github.com/neilime/zf2-mobile-detect/blob/master/composer.json#L21
into this:
```
    "zendframework/zend-mvc": "^2.7 || ^3.0",
```

**Comment by neilime** [comment]
Hi,
For sure you can create a pull request, Travis ci will tell us if its works with your change

Thanks
